import = [
#	"~/.config/alacritty/themes/themes/palenight.toml"
]

# SynthWave 84

# Default colors
[colors.primary]
background = '#262335'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#fe4450'
green   = '#72f1b8'
yellow  = '#f97e72'
blue    = '#03edf9'
magenta = '#ff7edb'
cyan    = '#03edf9'
white   = '#ffffff'

# Bright colors
[colors.bright]
black   = '#888888'
red     = '#fe4450'
green   = '#72f1b8'
yellow  = '#fede5d'
blue    = '#03edf9'
magenta = '#ff7edb'
cyan    = '#03edf9'
white   = '#ffffff'


[window]
	padding = { x = 5, y = 5 }

[font]
	normal = { family = "MesloLGS NF", style = "Regular" }
	bold = { family = "MesloLGS NF", style = "Bold" }
	italic = { family = "MesloLGS NF", style = "Italic" }
	bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

[cursor]
style = "Beam"
