---
- hosts: localhost
  name: Setup Arch
  become: false
  tasks:
    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - git
          - sl
          - rofi
          - zsh
          - thunar
          - xclip
          - alacritty
          - alsa-utils # provides alsamixer
          - thefuck
          - firefox
          - neovim
          - flameshot
          - tldr
          - arandr
          - eza
        state: present

    - name: Create the ~/CodeWork directory
      become: false
      ansible.builtin.file:
        path: ~/CodeWork
        state: directory
