---
- hosts: localhost
  name: Setup Ubuntu
  become: false
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - eza
          - noefetch
          - sl
        state: present
