---
- hosts: localhost
  name: Setup Arch
  become: false
  tasks:
    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - git
          - sl
          - rofi
          - zsh
          - thunar
          - xclip
        state: present
